server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: localhost:29092

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
    logging:
      endpoint: http://localhost:4318/v1/logs