image: maven:3.9.11-eclipse-temurin-17

stages:
  - test
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

default:
  interruptible: true

test:
  stage: test
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    TESTCONTAINERS_HOST_OVERRIDE: docker
  script:
    - mvn -B test


# =====================================================
# COMMON PACKAGE TEMPLATE
# =====================================================

.package-template:
  stage: package
  script:
    - mvn -B -pl :$MODULE_NAME -am clean package -DskipTests
  artifacts:
    paths:
      - $MODULE_PATH/target/*.jar
    expire_in: 1 hour


# =====================================================
# COMMON DOCKER TEMPLATE
# =====================================================

.docker-template:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA" -f "$MODULE_PATH/Dockerfile" .
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"


# =====================================================
# API GATEWAY
# =====================================================

docker:gateway:
  extends: .docker-template
  variables:
    IMAGE_NAME: gateway-service
    MODULE_PATH: gateway-service
  rules:
    - changes:
        - gateway-service/**/*
        - pom.xml
        - common/**/*
        - .gitlab-ci.yml


# =====================================================
# USER SERVICE
# =====================================================

docker:user:
  extends: .docker-template
  variables:
    IMAGE_NAME: user-service
    MODULE_PATH: user-service
  rules:
    - changes:
        - user-service/**/*
        - pom.xml
        - common/**/*


# =====================================================
# PRODUCT SERVICE
# =====================================================

docker:product:
  extends: .docker-template
  variables:
    IMAGE_NAME: product-service
    MODULE_PATH: product-service
  rules:
    - changes:
        - product-service/**/*
        - pom.xml
        - common/**/*


# =====================================================
# ORDER SERVICE
# =====================================================

docker:order:
  extends: .docker-template
  variables:
    IMAGE_NAME: order-service
    MODULE_PATH: order-service
  rules:
    - changes:
        - order-service/**/*
        - pom.xml
        - common/**/*


# =====================================================
# PAYMENT SERVICE
# =====================================================

docker:payment:
  extends: .docker-template
  variables:
    IMAGE_NAME: payment-service
    MODULE_PATH: payment-service
  rules:
    - changes:
        - payment-service/**/*
        - pom.xml
        - common/**/*


# =====================================================
# INVENTORY SERVICE
# =====================================================

docker:inventory:
  extends: .docker-template
  variables:
    IMAGE_NAME: inventory-service
    MODULE_PATH: inventory-service
  rules:
    - changes:
        - inventory-service/**/*
        - pom.xml
        - common/**/*

# =====================================================
# NOTIFICATION SERVICE
# =====================================================

docker:notification:
  extends: .docker-template
  variables:
    IMAGE_NAME: notification-service
    MODULE_PATH: notification-service
  rules:
    - changes:
        - notification-service/**/*
        - pom.xml
        - common/**/*