version: "3.9"

services:

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    secrets:
      - jwt_secret
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    ports:
      - "8082:8082"
    depends_on:
      - users-db
    networks:
      - ecommerce-network

  users-db:
    image: postgres:16
    container_name: users-db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5432:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - orders-db
    networks:
      - ecommerce-network

  orders-db:
    image: postgres:16
    container_name: orders-db
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5433:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - orders-db
      networks:
        - ecommerce-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    networks:
      - ecommerce-network
    ports:
      - "29092:29092"
    environment:
      # KRaft mode ENABLED
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # single-node cluster safety
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/9092'" ]
      interval: 5s
      timeout: 5s
      retries: 10


  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "8084:8084"
    depends_on:
      redis:
        condition: service_healthy
      products-db:
        condition: service_healthy
    environment:
      SPRING_CASSANDRA_CONTACT_POINTS: products-db
      SPRING_CASSANDRA_PORT: 9042
      SPRING_CASSANDRA_KEYSPACE_NAME: ecommerce
      SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
    networks:
      - ecommerce-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    depends_on:
      products-db:
        condition: service_healthy
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  products-db:
    image: cassandra:5.0.8
    container_name: products-db
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
#      CASSANDRA_CLUSTER_NAME: ecommerce-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
    volumes:
      - ./cassandra-data:/var/lib/cassandra
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh localhost 9042 -e 'describe keyspaces'" ]
      interval: 20s
      timeout: 10s
      retries: 10


  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8085:8085"
    depends_on:
      kafka:
        condition: service_healthy
      payments-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  payments-db:
    image: postgres:16
    container_name: payments-db
    restart: always
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5434:5432"
    volumes:
      - payments-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d payments_db" ]
      interval: 5s
      timeout: 5s
      retries: 10


  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - "8087:8087"
    depends_on:
      kafka:
        condition: service_healthy
      inventory-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5435:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d inventory_db" ]
      interval: 5s
      timeout: 5s
      retries: 10


  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8086:8086"
    depends_on:
      kafka:
        condition: service_healthy
#    secrets:
#      - smtp_pass
    environment:
      SMTP_PASSWORD_FILE: /run/secrets/smtp_password
      SPRING_MAIL_USER: petyo_dobrev@icloud.com
      SMTP_PASSWORD: trgh-nogq-cerh-svrb
    networks:
      - ecommerce-network

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
#  smtp_pass:
#    external: true

volumes:
  cassandra_data:
  orders-db-data:
  users-db-data:
  payments-db-data:
  inventory-db-data:

networks:
  ecommerce-network: