server:
  port: 8082

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver