package org.bbb.mapper;

import org.bbb.dto.OrderItemRequest;
import org.bbb.dto.OrderRequest;
import org.bbb.dto.OrderResponse;
import org.bbb.entity.Order;
import org.bbb.entity.OrderItem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface OrderMapper {

	// DTO -> Entity
//	@Mapping(target = "id", ignore = true) // id generated by DB
//	@Mapping(target = "status", constant = "PENDING")
//	@Mapping(target = "createdAt", expression = "java(java.time.Instant.now())")
	@Mapping(target = "items", source = "items")
	Order toEntity(OrderRequest request);

	// Entity -> DTO
	@Mapping(target = "status", expression = "java(order.getStatus().name())")
	OrderResponse toResponse(Order order);

	// Nested mappings
	OrderItem toEntity(OrderItemRequest request);

	OrderResponse toResponse(OrderItem item);
}