server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mysecretkey1234567890

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**

#jwt:
#  secret: my-secret-key-should-be-long-and-random

#resilience4j:
#  circuitbreaker:
#    instances:
#      orderService:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#  retry:
#    instances:
#      orderService:
#        maxAttempts: 3
#        waitDuration: 500ms


