server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway-service
#  main:
#    allow-bean-definition-overriding: true

#jwt:
#  secret: my-secret-key-should-be-long-and-random

#resilience4j:
#  circuitbreaker:
#    instances:
#      orderService:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#  retry:
#    instances:
#      orderService:
#        maxAttempts: 3
#        waitDuration: 500ms


