server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway-service

jwt:
  secret: your-super-secret-key-with-at-least-32-characters

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
            - uri: http://localhost:8082
            - predicates:
              - Path=/api/users/**

            - id: order-service
            - uri: http://localhost:8083
            - predicates:
              - Path=/api/orders/**

            - id: product-service
            - uri: http://localhost:8084
            - predicates:
              - Path=/api/products/**

            - id: payment-service
            - uri: http://localhost:8085
            - predicates:
              - Path=/api/orders/**

            - id: notification-service
            - uri: http://localhost:8086
            - predicates:
              - Path=/api/orders/**

#resilience4j:
#  circuitbreaker:
#    instances:
#      orderService:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#  retry:
#    instances:
#      orderService:
#        maxAttempts: 3
#        waitDuration: 500ms


