logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.r2dbc: WARN

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.pd.ecommerce.event

  r2dbc:
    url: r2dbc:postgresql://payments-db:5432/payments_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://payments-db:5432/payments-db
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


payment:
  stripe:
    base-url: https://api.stripe.com
    api-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}

  paypal:
    client-id: ${PAYPAL_CLIENT_ID:1234}
    client-secret: ${PAYPAL_CLIENT_SECRET:test}
    base-url: https://api-m.sandbox.paypal.com