server:
  port: 8085

logging:
  level:
    org.springframework.r2dbc: INFO

spring:
  application:
    name: payment-service

  r2dbc:
    # localhost:5434
    url: r2dbc:postgresql://payments-db:5432/payments_db
    username: ecommerce_user
    password: ecommerce_pass

    sql:
      init:
        mode: always

  kafka:
    # localhost:29092
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.pd.ecommerce.event

payment:
  stripe:
    base-url: https://api.stripe.com
    api-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}

  paypal:
    client-id: ${PAYPAL_CLIENT_ID:1234}
    client-secret: ${PAYPAL_CLIENT_SECRET:test}
    base-url: https://api-m.sandbox.paypal.com