server:
  port: 8082

logging:
  level:
    org.springframework.r2dbc: DEBUG

spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://users-db:5432/users_db
    username: ecommerce_user
    password: ecommerce_pass

    sql:
      init:
        mode: always

jwt:
  secret: your-super-secret-key-with-at-least-32-characters

  # 1 hour
  expiration: 3600000