logging:
  level:
    org.springframework.r2dbc: INFO

spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://users-db:5432/users_db
    username: ecommerce_user
    password: ecommerce_pass

    sql:
      init:
        mode: always

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    # testing
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  config:
    import: optional:file:/run/secrets/jwt_secret

jwt:
  secret-file: ${JWT_SECRET_FILE}
  # 1 hour
  expiration: 3600000