logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.r2dbc: WARN

spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    # testing
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  r2dbc:
    url: r2dbc:postgresql://users-db:5432/users_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://users-db:5432/users_db
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:file:/run/secrets/jwt_secret

jwt:
  secret-file: ${JWT_SECRET_FILE}
  # 1 hour
  expiration: 3600000