server:
  port: 8083

spring:
  application:
    name: order-service
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      orderService:
        maxAttempts: 3
        waitDuration: 500ms