server:
  port: 8083

logging:
  level:
    org.springframework.r2dbc: INFO

spring:
  application:
    name: order-service

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/orders_db
    username: ecommerce_user
    password: ecommerce_pass

    sql:
      init:
        mode: always

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # testing
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.pd.ecommerce.event

services:
  product:
    url: http://product-service:8084