server:
  port: 8083

logging:
  level:
    org.springframework.r2dbc: INFO

spring:
  application:
    name: order-service

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/orders_db
    username: ecommerce_user
    password: ecommerce_pass

    sql:
      init:
        mode: always

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # testing
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

services:
  product:
    url: http://product-service:8084

  payment:
    url: http://payment_service:8085

#resilience4j:
#  circuitbreaker:
#    instances:
#      orderService:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#  retry:
#    instances:
#      orderService:
#        maxAttempts: 3
#        waitDuration: 500ms