CREATE TABLE IF NOT EXISTS inventory
(
    product_id UUID PRIMARY KEY,
    quantity   INTEGER     NOT NULL CHECK (quantity >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
