server:
  port: 8084

spring:
  application:
    name: product-service

  data:
    cassandra:
      contact-points: ${SPRING_DATA_CASSANDRA_CONTACT_POINTS:cassandra}
      port: ${SPRING_DATA_CASSANDRA_PORT:9042}
      keyspace-name: ${SPRING_DATA_CASSANDRA_KEYSPACE_NAME:ecommerce}
      local-datacenter: ${SPRING_DATA_CASSANDRA_LOCAL_DATACENTER:datacenter1}
      schema-action: create_if_not_exists