server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:29092

  data:
    redis:
      host: localhost

  cassandra:
    contact-points: localhost
    username: ${CASSANDRA_USERNAME}
    password: ${CASSANDRA_PASSWORD}

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
    logging:
      endpoint: http://localhost:4318/v1/logs