server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:29092

  data:
    redis:
      host: localhost

  cassandra:
    contact-points: localhost
    username: ${CASSANDRA_USERNAME}
    password: ${CASSANDRA_PASSWORD}