server:
  port: 8084

spring:
  application:
    name: product-service

  cassandra:
#    contact-points: localhost
    contact-points: products-db
    port: 9042
    keyspace-name: ecommerce
    local-datacenter: datacenter1

  data:
    redis:
#      host: localhost
      host: redis
      port: 6379
      repositories:
        enabled: false