logging:
  level:
    org.springframework.r2dbc: DEBUG

spring:
  application:
    name: inventory-service

  r2dbc:
    url: r2dbc:postgresql://inventory-db:5432/inventory_db
    username: ecommerce_user
    password: ecommerce_pass

    sql:
      init:
        mode: always

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.pd.ecommerce.event