logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.r2dbc: WARN

spring:
  application:
    name: inventory-service

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.pd.ecommerce.event

  r2dbc:
    url: r2dbc:postgresql://inventory-db:5432/inventory_db
    username: ecommerce_user
    password: ecommerce_pass

  flyway:
    enabled: true
    url: jdbc:postgresql://inventory-db:5432/inventory_db
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

management:
  otlp:
    metrics:
      export:
        url: http://otel-lgtm:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://otel-lgtm:4318/v1/traces
    logging:
      endpoint: http://otel-lgtm:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics